In [2]:
import pandas as pd 

raw_05 = pd.read_csv("data/01_raw/sample_orig_2005.txt", 
                     sep = "|", 
                     header = None
                    )

raw_05.head(3)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,609,200503,N,202002,NaN,12,1,P,90,36,...,1,Other sellers,U.S. BANK N.A.,NaN,NaN,9,NaN,7,N,9
1,646,200505,N,203504,17140.0,0,1,P,77,43,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,7,N,9
2,729,200503,N,203502,NaN,0,1,P,61,33,...,2,Other sellers,"PNC MORTGAGE SERVICES, INC.",NaN,NaN,9,NaN,7,N,9

In [4]:
raw_05.shape

(50000, 32)

In [6]:
raw_05.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 32 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       50000 non-null  int64
 1   1       50000 non-null  int64
 2   2       50000 non-null  str
 3   3       50000 non-null  int64
 4   4       41916 non-null  float64
 5   5       50000 non-null  int64
 6   6       50000 non-null  int64
 7   7       50000 non-null  str
 8   8       50000 non-null  int64
 9   9       50000 non-null  int64
 10  10      50000 non-null  int64
 11  11      50000 non-null  int64
 12  12      50000 non-null  float64
 13  13      50000 non-null  str
 14  14      50000 non-null  str
 15  15      50000 non-null  str
 16  16      50000 non-null  str
 17  17      50000 non-null  str
 18  18      50000 non-null  int64
 19  19      50000 non-null  str
 20  20      50000 non-null  str
 21  21      50000 non-null  int64
 22  22      50000 non-null  int64
 23  23      50000 non-null  str
 24  24      50000 non-null  str
 25  25      0 non-null      float64
 26  26      0 non-null      float64
 27  27      50000 non-null  int64
 28  28      0 non-null      float64
 29  29      50000 non-null  int64
 30  30      50000 non-null  str
 31  31      50000 non-null  int64
dtypes: float64(5), int64(15), str(12)
memory usage: 15.5 MB

In [10]:
def assign_names(raw_data):
    
    ORIGINATION_COLUMNS = [
    "credit_score", "first_payment_date", "first_time_homebuyer_flag",
    "maturity_date", "msa", "mi_percentage", "number_of_units",
    "occupancy_status", "original_cltv", "original_dti", "original_upb",
    "original_ltv", "original_interest_rate", "channel",
    "prepayment_penalty_flag", "amortization_type", "property_state",
    "property_type", "postal_code", "loan_sequence_number", "loan_purpose",
    "original_loan_term", "number_of_borrowers", "seller_name",
    "servicer_name", "super_conforming_flag",
    "pre_relief_refinance_loan_sequence_number", "special_eligibility_program",
    "relief_refinance_indicator", "property_valuation_method",
    "interest_only_indicator", "mi_cancellation_indicator"
]

    raw_data.columns = ORIGINATION_COLUMNS

    return raw_data

In [11]:
assign_names(raw_05)

,credit_score,first_payment_date,first_time_homebuyer_flag,maturity_date,msa,mi_percentage,number_of_units,occupancy_status,original_cltv,original_dti,...,number_of_borrowers,seller_name,servicer_name,super_conforming_flag,pre_relief_refinance_loan_sequence_number,special_eligibility_program,relief_refinance_indicator,property_valuation_method,interest_only_indicator,mi_cancellation_indicator
0,609,200503,N,202002,NaN,12,1,P,90,36,...,1,Other sellers,U.S. BANK N.A.,NaN,NaN,9,NaN,7,N,9
1,646,200505,N,203504,17140.0,0,1,P,77,43,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,7,N,9
2,729,200503,N,203502,NaN,0,1,P,61,33,...,2,Other sellers,"PNC MORTGAGE SERVICES, INC.",NaN,NaN,9,NaN,7,N,9
3,748,200503,N,203502,NaN,0,1,P,68,26,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,7,N,9
4,810,200503,N,203502,43780.0,0,1,P,49,26,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,7,N,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,593,200601,N,203512,19124.0,0,1,P,80,23,...,2,"CITIMORTGAGE, INC.","CITIMORTGAGE, INC.",NaN,NaN,9,NaN,7,N,9
49996,790,200512,N,202511,45820.0,0,1,P,51,22,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,7,N,9
49997,670,201009,N,203511,18140.0,0,1,P,75,32,...,1,FIFTH THIRD BANK,FIFTH THIRD BANK,NaN,NaN,9,NaN,7,N,9
49998,619,200601,Y,203512,28140.0,0,1,P,97,44,...,1,"BANK OF AMERICA, N.A.","BANK OF AMERICA, N.A.",NaN,NaN,9,NaN,7,N,9
49999,607,200602,Y,203601,16974.0,0,1,P,97,36,...,1,"BANK OF AMERICA, N.A.","BANK OF AMERICA, N.A.",NaN,NaN,9,NaN,7,N,9